# Generated by Django 3.0.5 on 2020-04-29 21:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='pontosturistico',
            name='aprovado',
            field=models.BooleanField(default=False),
        ),
    ]
