# Generated by Django 3.0.5 on 2020-04-29 22:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atracoes', '0001_initial'),
        ('core', '0002_auto_20200429_2159'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontosturistico',
            name='atracoes',
            field=models.ManyToManyField(to='atracoes.Atracao'),
        ),
    ]
