# Generated by Django 3.0.5 on 2020-04-30 14:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentarios', '0001_initial'),
        ('core', '0003_pontosturistico_atracoes'),
    ]

    operations = [
        migrations.AddField(
            model_name='pontosturistico',
            name='comentarios',
            field=models.ManyToManyField(to='comentarios.Comentario'),
        ),
    ]
